package com.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_no
     *
     * @mbggenerated
     */
    private String prodNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sales_num
     *
     * @mbggenerated
     */
    private Integer salesNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock_warn
     *
     * @mbggenerated
     */
    private Integer stockWarn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.serial_id
     *
     * @mbggenerated
     */
    private Integer serialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img_detail
     *
     * @mbggenerated
     */
    private String imgDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.format_id
     *
     * @mbggenerated
     */
    private Integer formatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_inspect
     *
     * @mbggenerated
     */
    private String isInspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.onsale_time
     *
     * @mbggenerated
     */
    private Date onsaleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_no
     *
     * @return the value of product.prod_no
     *
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_no
     *
     * @param prodNo the value for product.prod_no
     *
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spec
     *
     * @return the value of product.spec
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spec
     *
     * @param spec the value for product.spec
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.place
     *
     * @return the value of product.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.place
     *
     * @param place the value for product.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sales_num
     *
     * @return the value of product.sales_num
     *
     * @mbggenerated
     */
    public Integer getSalesNum() {
        return salesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sales_num
     *
     * @param salesNum the value for product.sales_num
     *
     * @mbggenerated
     */
    public void setSalesNum(Integer salesNum) {
        this.salesNum = salesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock_warn
     *
     * @return the value of product.stock_warn
     *
     * @mbggenerated
     */
    public Integer getStockWarn() {
        return stockWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock_warn
     *
     * @param stockWarn the value for product.stock_warn
     *
     * @mbggenerated
     */
    public void setStockWarn(Integer stockWarn) {
        this.stockWarn = stockWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand_id
     *
     * @return the value of product.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand_id
     *
     * @param brandId the value for product.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.serial_id
     *
     * @return the value of product.serial_id
     *
     * @mbggenerated
     */
    public Integer getSerialId() {
        return serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.serial_id
     *
     * @param serialId the value for product.serial_id
     *
     * @mbggenerated
     */
    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img_url
     *
     * @return the value of product.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img_url
     *
     * @param imgUrl the value for product.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img_detail
     *
     * @return the value of product.img_detail
     *
     * @mbggenerated
     */
    public String getImgDetail() {
        return imgDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img_detail
     *
     * @param imgDetail the value for product.img_detail
     *
     * @mbggenerated
     */
    public void setImgDetail(String imgDetail) {
        this.imgDetail = imgDetail == null ? null : imgDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.format_id
     *
     * @return the value of product.format_id
     *
     * @mbggenerated
     */
    public Integer getFormatId() {
        return formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.format_id
     *
     * @param formatId the value for product.format_id
     *
     * @mbggenerated
     */
    public void setFormatId(Integer formatId) {
        this.formatId = formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_inspect
     *
     * @return the value of product.is_inspect
     *
     * @mbggenerated
     */
    public String getIsInspect() {
        return isInspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_inspect
     *
     * @param isInspect the value for product.is_inspect
     *
     * @mbggenerated
     */
    public void setIsInspect(String isInspect) {
        this.isInspect = isInspect == null ? null : isInspect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.onsale_time
     *
     * @return the value of product.onsale_time
     *
     * @mbggenerated
     */
    public Date getOnsaleTime() {
        return onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.onsale_time
     *
     * @param onsaleTime the value for product.onsale_time
     *
     * @mbggenerated
     */
    public void setOnsaleTime(Date onsaleTime) {
        this.onsaleTime = onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status_id
     *
     * @return the value of product.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status_id
     *
     * @param statusId the value for product.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remarks
     *
     * @return the value of product.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remarks
     *
     * @param remarks the value for product.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}