/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-09-04 07:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!--\n");
      out.write("        ===\n");
      out.write("        This comment should NOT be removed.\n");
      out.write("\n");
      out.write("        Charisma v2.0.0\n");
      out.write("\n");
      out.write("        Copyright 2012-2014 Muhammad Usman\n");
      out.write("        Licensed under the Apache License v2.0\n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("        http://usman.it\n");
      out.write("        http://twitter.com/halalit_usman\n");
      out.write("        ===\n");
      out.write("    -->\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("    <title>登录</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.\">\n");
      out.write("    <meta name=\"author\" content=\"Muhammad Usman\">\n");
      out.write("\n");
      out.write("    <!-- The styles -->\n");
      out.write("    <link id=\"bs-css\" href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"css/charisma-app.css\" rel=\"stylesheet\">\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>\n");
      out.write("    <link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/colorbox/example3/colorbox.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/responsive-tables/responsive-tables.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>\n");
      out.write("    <link href='css/jquery.noty.css' rel='stylesheet'>\n");
      out.write("    <link href='css/noty_theme_default.css' rel='stylesheet'>\n");
      out.write("    <link href='css/elfinder.min.css' rel='stylesheet'>\n");
      out.write("    <link href='css/elfinder.theme.css' rel='stylesheet'>\n");
      out.write("    <link href='css/jquery.iphone.toggle.css' rel='stylesheet'>\n");
      out.write("    <link href='css/uploadify.css' rel='stylesheet'>\n");
      out.write("    <link href='css/animate.min.css' rel='stylesheet'>\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"bower_components/jquery/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- The fav icon -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"ch-container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        \n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12 center login-header\">\n");
      out.write("            <h2>Welcome to Charisma</h2>\n");
      out.write("        </div>\n");
      out.write("        <!--/span-->\n");
      out.write("    </div><!--/row-->\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"well col-md-5 center login-box\">\n");
      out.write("            <div class=\"alert alert-info\">\n");
      out.write("                会员登录 \n");
      out.write("            </div>\n");
      out.write("            <form class=\"form-horizontal\" action=\"index.html\" method=\"post\">\n");
      out.write("                <fieldset>\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user red\"></i></span>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Username\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"></div><br>\n");
      out.write("\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock red\"></i></span>\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"Password\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- \n");
      out.write("                    <div class=\"input-prepend\">\n");
      out.write("                        <label class=\"remember\" for=\"remember\"><input type=\"checkbox\" id=\"remember\"> Remember me</label>\n");
      out.write("                    </div>\n");
      out.write("                     -->\n");
      out.write("                     \n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("                    <p class=\"center col-md-5\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Login</button>\n");
      out.write("                    </p>\n");
      out.write("                </fieldset>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <!--/span-->\n");
      out.write("    </div><!--/row-->\n");
      out.write("</div><!--/fluid-row-->\n");
      out.write("\n");
      out.write("</div><!--/.fluid-container-->\n");
      out.write("\n");
      out.write("<!-- external javascript -->\n");
      out.write("\n");
      out.write("<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- library for cookie management -->\n");
      out.write("<script src=\"js/jquery.cookie.js\"></script>\n");
      out.write("<!-- calender plugin -->\n");
      out.write("<script src='bower_components/moment/min/moment.min.js'></script>\n");
      out.write("<script src='bower_components/fullcalendar/dist/fullcalendar.min.js'></script>\n");
      out.write("<!-- data table plugin -->\n");
      out.write("<script src='js/jquery.dataTables.min.js'></script>\n");
      out.write("\n");
      out.write("<!-- select or dropdown enhancer -->\n");
      out.write("<script src=\"bower_components/chosen/chosen.jquery.min.js\"></script>\n");
      out.write("<!-- plugin for gallery image view -->\n");
      out.write("<script src=\"bower_components/colorbox/jquery.colorbox-min.js\"></script>\n");
      out.write("<!-- notification plugin -->\n");
      out.write("<script src=\"js/jquery.noty.js\"></script>\n");
      out.write("<!-- library for making tables responsive -->\n");
      out.write("<script src=\"bower_components/responsive-tables/responsive-tables.js\"></script>\n");
      out.write("<!-- tour plugin -->\n");
      out.write("<script src=\"bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js\"></script>\n");
      out.write("<!-- star rating plugin -->\n");
      out.write("<script src=\"js/jquery.raty.min.js\"></script>\n");
      out.write("<!-- for iOS style toggle switch -->\n");
      out.write("<script src=\"js/jquery.iphone.toggle.js\"></script>\n");
      out.write("<!-- autogrowing textarea plugin -->\n");
      out.write("<script src=\"js/jquery.autogrow-textarea.js\"></script>\n");
      out.write("<!-- multiple file upload plugin -->\n");
      out.write("<script src=\"js/jquery.uploadify-3.1.min.js\"></script>\n");
      out.write("<!-- history.js for cross-browser state change on ajax -->\n");
      out.write("<script src=\"js/jquery.history.js\"></script>\n");
      out.write("<!-- application script for Charisma demo -->\n");
      out.write("<script src=\"js/charisma.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
