/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-09-18 06:30:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProductImage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/Juyan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ordering_system/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/leftMenu.jsp", Long.valueOf(1474173372643L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1461759242601L));
    _jspx_dependants.put("/topbar.jsp", Long.valueOf(1473090587416L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1473329120823L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <!--\r\n");
      out.write("        ===\r\n");
      out.write("        This comment should NOT be removed.\r\n");
      out.write("\r\n");
      out.write("        Charisma v2.0.0\r\n");
      out.write("\r\n");
      out.write("        Copyright 2012-2014 Muhammad Usman\r\n");
      out.write("        Licensed under the Apache License v2.0\r\n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\r\n");
      out.write("\r\n");
      out.write("        http://usman.it\r\n");
      out.write("        http://twitter.com/halalit_usman\r\n");
      out.write("        ===\r\n");
      out.write("    -->\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <title>添加销售属性</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.\">\r\n");
      out.write("    <meta name=\"author\" content=\"Muhammad Usman\">\r\n");
      out.write("\r\n");
      out.write("    <!-- The styles -->\r\n");
      out.write("    <link id=\"bs-css\" href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>\r\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>\r\n");
      out.write("    <link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='bower_components/colorbox/example3/colorbox.css' rel='stylesheet'>\r\n");
      out.write("    <link href='bower_components/responsive-tables/responsive-tables.css' rel='stylesheet'>\r\n");
      out.write("    <link href='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/jquery.noty.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/noty_theme_default.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/elfinder.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/elfinder.theme.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/jquery.iphone.toggle.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/uploadify.css' rel='stylesheet'>\r\n");
      out.write("    <link href='css/animate.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"bower_components/jquery/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- The fav icon -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- my custom css -->\r\n");
      out.write("\t<link href='css/custom.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- topbar -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- topbar starts -->\r\n");
      out.write("    <div class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle pull-left animated flip\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\"> <img alt=\"Charisma Logo\" src=\"img/logo20.png\" class=\"hidden-xs\" \r\n");
      out.write("            \tstyle=\"width:72px;height:38px\"/></a>\r\n");
      out.write("\r\n");
      out.write("            <!-- user dropdown starts -->\r\n");
      out.write("            <div class=\"btn-group pull-right\">\r\n");
      out.write("                <button class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                    <i class=\"glyphicon glyphicon-user\"></i><span class=\"hidden-sm hidden-xs\"> \r\n");
      out.write("                    \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"caret\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a href=\"#\">账户设置</a></li>\r\n");
      out.write("                    <li class=\"divider\"></li>\r\n");
      out.write("                    <li><a href=\"login.html\">退出</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- user dropdown ends -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"collapse navbar-collapse nav navbar-nav top-menu\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-info-sign\"></i> 关于聚妍 <span\r\n");
      out.write("                            class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"#\">公司介绍</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"#\">OPI</a></li>\r\n");
      out.write("                        <li><a href=\"#\">贝瑞可</a></li>\r\n");
      out.write("                        <li><a href=\"#\">CND</a></li>\r\n");
      out.write("                        <li><a href=\"#\">YOUKA</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"glyphicon glyphicon-globe\"></i> 最近消息及活动</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"glyphicon glyphicon-star\"></i> 联系方式</a></li>               \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- topbar ends -->");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<div class=\"ch-container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- topbar -->\r\n");
      out.write("\t\t");
      out.write("\t\r\n");
      out.write("\t<!-- left menu starts -->\r\n");
      out.write("        <div class=\"col-sm-2 col-lg-2\">\r\n");
      out.write("            <div class=\"sidebar-nav\">\r\n");
      out.write("                <div class=\"nav-canvas\">\r\n");
      out.write("                    <div class=\"nav-sm nav nav-stacked\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"nav nav-pills nav-stacked main-menu\">\r\n");
      out.write("                        <li class=\"nav-header\">Main</li>\r\n");
      out.write("                        <li class=\"accordion\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"glyphicon glyphicon-plus\"></i><span> 商品管理</span></a>\r\n");
      out.write("                            <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("                                <li><a href=\"addProduct.jsp\">添加新商品</a></li>\r\n");
      out.write("                                <li><a href=\"#\">商品管理</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"index.html\"><i class=\"glyphicon glyphicon-home\"></i><span> Dashboard</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"ui.html\"><i class=\"glyphicon glyphicon-eye-open\"></i><span> UI Features</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"form.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-edit\"></i><span> Forms</span></a></li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"chart.html\"><i class=\"glyphicon glyphicon-list-alt\"></i><span> Charts</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"typography.html\"><i class=\"glyphicon glyphicon-font\"></i><span> Typography</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"gallery.html\"><i class=\"glyphicon glyphicon-picture\"></i><span> Gallery</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-header hidden-md\">Sample Section</li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"table.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-align-justify\"></i><span> Tables</span></a></li>\r\n");
      out.write("                        <li class=\"accordion\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"glyphicon glyphicon-plus\"></i><span> Accordion Menu</span></a>\r\n");
      out.write("                            <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("                                <li><a href=\"#\">Child Menu 1</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Child Menu 2</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"calendar.html\"><i class=\"glyphicon glyphicon-calendar\"></i><span> Calendar</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"grid.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-th\"></i><span> Grid</span></a></li>\r\n");
      out.write("                        <li><a href=\"tour.html\"><i class=\"glyphicon glyphicon-globe\"></i><span> Tour</span></a></li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"icon.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-star\"></i><span> Icons</span></a></li>\r\n");
      out.write("                        <li><a href=\"error.html\"><i class=\"glyphicon glyphicon-ban-circle\"></i><span> Error Page</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"login.html\"><i class=\"glyphicon glyphicon-lock\"></i><span> Login Page</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <label id=\"for-is-ajax\" for=\"is-ajax\"><input id=\"is-ajax\" type=\"checkbox\"> Ajax on menu</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/span-->\r\n");
      out.write("        <!-- left menu ends -->");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\" class=\"col-lg-10 col-sm-10\">\r\n");
      out.write("            <!-- content starts -->\r\n");
      out.write("            \r\n");
      out.write("            <!-- \r\n");
      out.write("            <div>\r\n");
      out.write("\t\t\t    <ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t            <a href=\"#\">首页</a>\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t            <a href=\"#\">添加销售属性</a>\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t    <div class=\"box col-md-12\">\r\n");
      out.write("\t\t\t        <div class=\"box-inner\">\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t            <div class=\"box-header well\" data-original-title=\"\">\r\n");
      out.write("\t\t\t                <h2><i class=\"glyphicon glyphicon-edit\"></i> 添加销售属性</h2>     \r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t            <div class=\"box-content\">\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t\t                <table id=\"dataTable\" class=\"table\">\r\n");
      out.write("\t\t\t                \t<thead>\r\n");
      out.write("\t\t\t                        <tr>\r\n");
      out.write("\t\t\t                            <th>sku编码</th>\r\n");
      out.write("\t\t\t                            <th>属性名称</th>\r\n");
      out.write("\t\t\t                            <th>属性图片</th>\r\n");
      out.write("\t\t\t                            <th>属性描述</th>\r\n");
      out.write("\t\t\t                            <th>价格（元）</th>\r\n");
      out.write("\t\t\t                            <th>是否卫检</th>\r\n");
      out.write("\t\t\t                            <th>库存（件）</th>\r\n");
      out.write("\t\t\t                            <th>警戒库存（件）</th>\r\n");
      out.write("\t\t\t                            <th>上架时间</th>\r\n");
      out.write("\t\t\t                            <th>状态</th>\r\n");
      out.write("\t\t\t                            <th>操作</th>\r\n");
      out.write("\t\t\t                        </tr>\r\n");
      out.write("\t\t\t                 \t</thead>\r\n");
      out.write("\t\t\t                    <tbody>\r\n");
      out.write("\t\t\t                    \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("                        \t\t</tbody>\t\t\t                 \r\n");
      out.write("\t\t\t                </table>\r\n");
      out.write("\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t        <div style=\"margin:80px 10px 10px 80px;\">   \r\n");
      out.write("\t\t\t\t\t\t        <i id=\"add\" class=\"glyphicon glyphicon-edit\" >\r\n");
      out.write("\t\t\t\t\t          \t\t<label>添加新属性</label></i>\r\n");
      out.write("\t\t\t\t\t          \t<br>\r\n");
      out.write("\t\t\t\t\t          \t<div id=\"msg\" class=\"warn-msg\">");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t          \t<br>\r\n");
      out.write("\t\t\t\t          \t</div> \r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"form\" class=\"add-new\">\t\t\t                 \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t            \t<table>\r\n");
      out.write("\t\t\t\t            \t\t<tr>\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">sku编码 </td>\r\n");
      out.write("\t\t\t\t                \t\t<td>\r\n");
      out.write("\t\t\t\t                \t\t\t<input type=\"text\" name=\"sku\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t                \t\t</td>\r\n");
      out.write("\t\t\t\t                 \t\t<td id=\"prodNo_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">属性名称</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t                        <select name=\"attrName\" data-rel=\"chosen\">\r\n");
      out.write("\t\t\t\t\t\t                            <option>颜色分类</option>\r\n");
      out.write("\t\t\t\t\t\t                            <option>规格</option>\r\n");
      out.write("\t\t\t\t\t\t                        </select>\r\n");
      out.write("\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"attrName_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t              \t</tr>\r\n");
      out.write("\t\t\t\t\t              \t\r\n");
      out.write("\t\t\t\t\t              \t<tr>\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">属性图片</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<a id=\"img_href\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t             \t\t\t<img id=\"img_src\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onload=\"onPreviewLoad(this,50)\"/>\r\n");
      out.write("\t\t\t\t\t\t               \t\t</a>\r\n");
      out.write("\t\t\t\t\t\t               \t\t<input type=\"hidden\" id=\"image\" name=\"image\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<input type=\"file\" id=\"image_upload\" data-no-uniform=\"true\" />\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td id=\"image_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t            \t\t\r\n");
      out.write("\t\t\t\t\t            \t\t<td class=\"title\">属性描述</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<textarea name=\"description\" class=\"form-control\" rows=\"3\" \r\n");
      out.write("\t\t\t\t\t            \t\t\t\tplaceholder=\"如NLB44淡绿色、120ml等\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t                \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"description_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t              \t</tr>\r\n");
      out.write("\t\t\t\t\t              \t\r\n");
      out.write("\t\t\t\t\t          \t\t<tr>\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">价格（元）</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<input type=\"text\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"price_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">是否卫检</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t                        <select name=\"isInspect\" data-rel=\"chosen\">\r\n");
      out.write("\t\t\t\t\t\t                            <option value='Y'>是</option>\r\n");
      out.write("\t\t\t\t\t\t                            <option value='N'>否</option>\r\n");
      out.write("\t\t\t\t\t\t                        </select>\r\n");
      out.write("\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"attrName_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t              \t</tr>\r\n");
      out.write("\t\t\t\t\t              \t\r\n");
      out.write("\t\t\t\t\t              \t<tr>\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">库存（件）</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<input type=\"text\" name=\"stock\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"stock_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">警戒库存（件）</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<input type=\"text\" name=\"stockWarn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stockWarn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"stockWarn_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t              \t</tr>\r\n");
      out.write("\t\t\t\t\t              \t\t\r\n");
      out.write("\t\t\t\t\t              \t<tr>\r\n");
      out.write("\t\t\t\t            \t\t\t<td class=\"title\">上架时间</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<input type=\"text\" name=\"onsaleTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${onsaleTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t            \t\t\t\tclass=\"form-control form_date\" placeholder=\"格式yyyy-mm-dd\"/>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"onsaleTime_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t                \t\t\r\n");
      out.write("\t\t\t\t                \t\t<td class=\"title\">状态</td>\r\n");
      out.write("\t\t\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t\t\t            \t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t                        <select name=\"status\" data-rel=\"chosen\">\r\n");
      out.write("\t\t\t\t\t\t                            <option value=\"1\">待售</option>\r\n");
      out.write("\t\t\t\t\t\t                            <option value=\"2\">在售</option>\r\n");
      out.write("\t\t\t\t\t\t                            <option value=\"3\">下架</option>\r\n");
      out.write("\t\t\t\t\t\t                        </select>\r\n");
      out.write("\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t\t                \t\t<td id=\"status_warn\" class=\"warn-msg\"></td>\r\n");
      out.write("\t\t\t\t\t              \t</tr>\t\r\n");
      out.write("\t\t\t\t\t              \t\r\n");
      out.write("\t\t\t\t\t              \t<tr>\r\n");
      out.write("\t\t\t\t\t              \t\t<!-- 此处仅供测试使用，实际运行改回name=\"prodNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" -->\r\n");
      out.write("\t\t\t\t\t              \t\t<td><input type=\"hidden\" name=\"prodNo\" value=\"JY002\"/></td>\r\n");
      out.write("\t\t\t\t            \t\t\t<td><button type=\"button\" id=\"save\" class=\"btn btn-primary\" \r\n");
      out.write("\t\t\t\t            \t\t\t\tstyle=\"width:100px\">保存</button></td>\r\n");
      out.write("\t\t\t\t            \t\t\t<td><td>\r\n");
      out.write("\t\t\t\t            \t\t\t\t\t\t\t\t            \t\t\t\r\n");
      out.write("\t\t\t\t            \t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("    \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t            </form>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <!--/span-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div><!--/row-->\r\n");
      out.write("\r\n");
      out.write("\t    <!-- content ends -->\r\n");
      out.write("\t    </div><!--/#content.col-md-0-->\r\n");
      out.write("\t</div><!--/fluid-row-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("    <footer class=\"row\">\r\n");
      out.write("        <p class=\"col-md-9 col-sm-9 col-xs-12 copyright\">&copy; Juyan 2016 - 2017</p>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"col-md-3 col-sm-3 col-xs-12 powered-by\"><a href=\"\" class=\"link\">联系客服</a></p>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--/.fluid-container-->\r\n");
      out.write("\r\n");
      out.write("<!-- external javascript -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- library for cookie management -->\r\n");
      out.write("<script src=\"js/jquery.cookie.js\"></script>\r\n");
      out.write("<!-- calender plugin -->\r\n");
      out.write("<script src='bower_components/moment/min/moment.min.js'></script>\r\n");
      out.write("<script src='bower_components/fullcalendar/dist/fullcalendar.min.js'></script>\r\n");
      out.write("<!-- data table plugin -->\r\n");
      out.write("<script src='js/jquery.dataTables.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- select or dropdown enhancer -->\r\n");
      out.write("<script src=\"bower_components/chosen/chosen.jquery.min.js\"></script>\r\n");
      out.write("<!-- plugin for gallery image view -->\r\n");
      out.write("<script src=\"bower_components/colorbox/jquery.colorbox-min.js\"></script>\r\n");
      out.write("<!-- notification plugin -->\r\n");
      out.write("<script src=\"js/jquery.noty.js\"></script>\r\n");
      out.write("<!-- library for making tables responsive -->\r\n");
      out.write("<script src=\"bower_components/responsive-tables/responsive-tables.js\"></script>\r\n");
      out.write("<!-- tour plugin -->\r\n");
      out.write("<script src=\"bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js\"></script>\r\n");
      out.write("<!-- star rating plugin -->\r\n");
      out.write("<script src=\"js/jquery.raty.min.js\"></script>\r\n");
      out.write("<!-- for iOS style toggle switch -->\r\n");
      out.write("<script src=\"js/jquery.iphone.toggle.js\"></script>\r\n");
      out.write("<!-- autogrowing textarea plugin -->\r\n");
      out.write("<script src=\"js/jquery.autogrow-textarea.js\"></script>\r\n");
      out.write("<!-- multiple file upload plugin -->\r\n");
      out.write("<script src=\"js/jquery.uploadify-3.1.min.js\"></script>\r\n");
      out.write("<!-- history.js for cross-browser state change on ajax -->\r\n");
      out.write("<script src=\"js/jquery.history.js\"></script>\r\n");
      out.write("<!-- application script for Charisma demo -->\r\n");
      out.write("<script src=\"js/charisma.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- datepicker  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap-datetimepicker.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap-datetimepicker.zh-CN.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("<!-- my custom js -->\r\n");
      out.write("<script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function deleteRow(sender,sku){\r\n");
      out.write("\t//if (window.confirm(\"确认删除？\"))\r\n");
      out.write("\tvar prodNo = $(\"*[name='prodNo']\").val();\r\n");
      out.write("\tif(prodNo != null || prodNo != '') {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"removeProductSalesattr\",\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tsku: sku,\r\n");
      out.write("\t\t\t\tprodNo: prodNo\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tif(data == '') {\r\n");
      out.write("\t\t\t\t\t$(sender).parent().parent().remove();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#msg\").html(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\talert(\"删除属性失败\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#save\").click(function(){\r\n");
      out.write("\t\tvar map = {};\r\n");
      out.write("\t\t$(\"input\").each(function(){\r\n");
      out.write("\t\t\tif($(this).attr(\"type\") == 'text' || $(this).attr(\"type\") == 'hidden') {\r\n");
      out.write("\t\t\t\tvar name = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tif(name != undefined)\r\n");
      out.write("\t\t    \t\tmap[name] = $(this).val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"textarea\").each(function(){\r\n");
      out.write("\t\t\tmap[$(this).attr(\"name\")] = $(this).val();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"select\").each(function(){\r\n");
      out.write("\t\t\tmap[$(this).attr(\"name\")] = $(this).find(\"option:selected\").text();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t$.each(map, function(index, value) { \r\n");
      out.write("\t\t\talert(index + ':' + value); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar form_data = decodeURIComponent($(\"#form\").serialize(),true);\r\n");
      out.write("\r\n");
      out.write("\t\tvar sku = $(\"*[name='sku']\").val();\r\n");
      out.write("\t\tif(sku != null && sku != ''){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t   \ttype: \"POST\",\r\n");
      out.write("\t\t\t   \turl: \"addProductSalesattr\",\r\n");
      out.write("\t\t\t   \tdata: form_data,\r\n");
      out.write("\t\t\t   \tdataType:\"text\",\r\n");
      out.write("\t\t\t   \tsuccess: function(data){\r\n");
      out.write("\t\t\t   \t\tif(data == '') {\r\n");
      out.write("\t\t\t\t   \t\t$(\".add-new\").slideToggle();\r\n");
      out.write("\t\t\t\t   \t\t$(\"#dataTable\").append(\"<tr><td>\" + map['sku'] + \"</td><td>\" + map['attrName'] + \"</td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t  \t\t\"<a href='\" + map['image'] + \"'><img src='\" + map['image'] + \"' class='small'/></a></td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t   \t\tmap['description'] + \"</td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t   \t\tmap['price'] + \"</td><td>\" + map['isInspect'] + \"</td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t   \t\tmap['stock'] + \"</td><td>\" + map['stockWarn'] + \"</td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t  \t\tmap['onsaleTime'] + \"</td><td>\" + map['status'] + \"</td><td>\" +\r\n");
      out.write("\t\t\t\t\t\t  \t\t\"<a class='glyphicon glyphicon-trash link' onclick='deleteRow(this,\" + \r\n");
      out.write("\t\t\t\t\t\t  \t\tmap['sku'] + \")'></a></td></tr>\"\t\t\t   \t\r\n");
      out.write("\t\t\t\t\t   \t);\t\t\r\n");
      out.write("\t\t\t\t   \t\t$(\"#msg\").html(\"\");\r\n");
      out.write("\t\t\t   \t\t} else {\r\n");
      out.write("\t\t\t   \t\t\t$(\"#msg\").html(data);\r\n");
      out.write("\t\t\t   \t\t}\r\n");
      out.write("\t\t\t   \t},\r\n");
      out.write("\t\t\t   \terror: function(){\r\n");
      out.write("\t\t\t    \talert(\"添加新属性失败\");\r\n");
      out.write("\t\t\t   \t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /addProductImage.jsp(108,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/addProductImage.jsp(108,24) '${ProductSalesattrList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ProductSalesattrList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProductImage.jsp(108,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("prodSalesattr");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("    \t\r\n");
          out.write("                        \t\t\t\t<tr>                      \t\t\r\n");
          out.write("                        \t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.sku}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.attrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>\r\n");
          out.write("\t\t\t\t                           \t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.attrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t                            \t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.attrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"small\"/>\r\n");
          out.write("\t\t\t\t                            \t</a>\r\n");
          out.write("\t\t\t\t                            </td>\r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\t\t\t\t                            \r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>\r\n");
          out.write("\t\t\t\t                            \t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                            \t");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                            </td>\r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.stockWarn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.onsaleTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t                            <td>\r\n");
          out.write("\t\t\t\t                            \t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                            \t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                            \t");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                            </td> \r\n");
          out.write("\t\t\t\t                            <td>\r\n");
          out.write("\t\t\t\t                            \t<a class=\"glyphicon glyphicon-trash link\"\r\n");
          out.write("\t\t\t\t                            \t\tonclick=\"deleteRow(this,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.sku}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("\t\t\t\t                            \t</a>\r\n");
          out.write("\t\t\t\t                            </td>\r\n");
          out.write("                        \t\t\t\t</tr>\r\n");
          out.write("                        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /addProductImage.jsp(120,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.isInspect == 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t                            \t\t<span class=\"label-success label-default label\">是</span>\r\n");
        out.write("\t\t\t\t                            \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /addProductImage.jsp(123,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.isInspect == 'N'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t                            \t\t<span class=\"label-default label\">否</span>\r\n");
        out.write("\t\t\t\t                            \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /addProductImage.jsp(131,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.status == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t                            \t\t<span class=\"label-default label label-danger\">待售</span>\r\n");
        out.write("\t\t\t\t                            \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /addProductImage.jsp(134,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.status == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t                            \t\t<span class=\"label-default label label-success\">在售</span>\r\n");
        out.write("\t\t\t\t                            \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /addProductImage.jsp(137,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodSalesattr.status == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t                            \t\t<span class=\"label-default label\">下架</span>\r\n");
        out.write("\t\t\t\t                            \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent(null);
    // /addProductImage.jsp(156,47) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }
}
