/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-09-07 09:03:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Juyan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ordering_system/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1461759242601L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!--\n");
      out.write("        ===\n");
      out.write("        This comment should NOT be removed.\n");
      out.write("\n");
      out.write("        Charisma v2.0.0\n");
      out.write("\n");
      out.write("        Copyright 2012-2014 Muhammad Usman\n");
      out.write("        Licensed under the Apache License v2.0\n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("        http://usman.it\n");
      out.write("        http://twitter.com/halalit_usman\n");
      out.write("        ===\n");
      out.write("    -->\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("    <title>个人用户登录</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.\">\n");
      out.write("    <meta name=\"author\" content=\"Muhammad Usman\">\n");
      out.write("\n");
      out.write("    <!-- The styles -->\n");
      out.write("    <link id=\"bs-css\" href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"css/charisma-app.css\" rel=\"stylesheet\">\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>\n");
      out.write("    <link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/colorbox/example3/colorbox.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/responsive-tables/responsive-tables.css' rel='stylesheet'>\n");
      out.write("    <link href='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>\n");
      out.write("    <link href='css/jquery.noty.css' rel='stylesheet'>\n");
      out.write("    <link href='css/noty_theme_default.css' rel='stylesheet'>\n");
      out.write("    <link href='css/elfinder.min.css' rel='stylesheet'>\n");
      out.write("    <link href='css/elfinder.theme.css' rel='stylesheet'>\n");
      out.write("    <link href='css/jquery.iphone.toggle.css' rel='stylesheet'>\n");
      out.write("    <link href='css/uploadify.css' rel='stylesheet'>\n");
      out.write("    <link href='css/animate.min.css' rel='stylesheet'>\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"bower_components/jquery/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- The fav icon -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\">\n");
      out.write("\n");
      out.write("\t<!-- my custom css -->\n");
      out.write("\t<link href='css/custom.css' rel='stylesheet'>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"ch-container\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t        \n");
      out.write("\t    <div class=\"row\">\n");
      out.write("\t        <div class=\"col-md-12 center login-header\">\n");
      out.write("\t            <img alt=\"Charisma Logo\" src=\"img/logo20.png\" class=\"hidden-xs\" \n");
      out.write("\t            \tstyle=\"width:144px;height:76px\"/>\n");
      out.write("\t        </div>\n");
      out.write("\t        <!--/span-->\n");
      out.write("\t    </div><!--/row-->\n");
      out.write("\t\n");
      out.write("\t    <div class=\"row\">\n");
      out.write("\t        <div class=\"well col-md-4 center login-box\">\n");
      out.write("\t            \n");
      out.write("\t            <form class=\"form-horizontal\" action=\"login\" method=\"post\">\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user red\"></i></span>\n");
      out.write("                        <input type=\"text\" id=\"account\" name=\"account\" class=\"form-control\" placeholder=\"账号/手机号\">\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock red\"></i></span>\n");
      out.write("                        <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"密码\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("\t\t\t\t\t<div style=\"color:red; margin-top:10px;\">\n");
      out.write("                    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t        </div>\n");
      out.write(" \n");
      out.write("                    <div class=\"input-prepend\">\n");
      out.write("                        <div style=\"float:left\">\n");
      out.write("                        \t<input type=\"checkbox\" id=\"remember\"> 记住账号</input>\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"float:right\">\n");
      out.write("                        \t<a href=\"\"> 忘记密码?</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>    \n");
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"roleNo\" value=\"4\"/>\n");
      out.write("\t\t\t\t\t\n");
      out.write("                   \t<button type=\"submit\" class=\"btn btn-default\" onclick=\"rememberUser()\">登录</button>\n");
      out.write("\n");
      out.write("                   \t<button type=\"button\" class=\"btn\" onclick=\"location='register.jsp'\">免费注册</button>\n");
      out.write("\t            </form>\n");
      out.write("\t        </div>\n");
      out.write("\t        <!--/span-->\n");
      out.write("\t    </div><!--/row-->\n");
      out.write("\t</div><!--/fluid-row-->\n");
      out.write("\t\n");
      out.write("</div><!--/.fluid-container-->\n");
      out.write("\n");
      out.write("<!-- external javascript -->\n");
      out.write("\n");
      out.write("<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- library for cookie management -->\n");
      out.write("<script src=\"js/jquery.cookie.js\"></script>\n");
      out.write("<!-- calender plugin -->\n");
      out.write("<script src='bower_components/moment/min/moment.min.js'></script>\n");
      out.write("<script src='bower_components/fullcalendar/dist/fullcalendar.min.js'></script>\n");
      out.write("<!-- data table plugin -->\n");
      out.write("<script src='js/jquery.dataTables.min.js'></script>\n");
      out.write("\n");
      out.write("<!-- select or dropdown enhancer -->\n");
      out.write("<script src=\"bower_components/chosen/chosen.jquery.min.js\"></script>\n");
      out.write("<!-- plugin for gallery image view -->\n");
      out.write("<script src=\"bower_components/colorbox/jquery.colorbox-min.js\"></script>\n");
      out.write("<!-- notification plugin -->\n");
      out.write("<script src=\"js/jquery.noty.js\"></script>\n");
      out.write("<!-- library for making tables responsive -->\n");
      out.write("<script src=\"bower_components/responsive-tables/responsive-tables.js\"></script>\n");
      out.write("<!-- tour plugin -->\n");
      out.write("<script src=\"bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js\"></script>\n");
      out.write("<!-- star rating plugin -->\n");
      out.write("<script src=\"js/jquery.raty.min.js\"></script>\n");
      out.write("<!-- for iOS style toggle switch -->\n");
      out.write("<script src=\"js/jquery.iphone.toggle.js\"></script>\n");
      out.write("<!-- autogrowing textarea plugin -->\n");
      out.write("<script src=\"js/jquery.autogrow-textarea.js\"></script>\n");
      out.write("<!-- multiple file upload plugin -->\n");
      out.write("<script src=\"js/jquery.uploadify-3.1.min.js\"></script>\n");
      out.write("<!-- history.js for cross-browser state change on ajax -->\n");
      out.write("<script src=\"js/jquery.history.js\"></script>\n");
      out.write("<!-- application script for Charisma demo -->\n");
      out.write("<script src=\"js/charisma.js\"></script>\n");
      out.write("\n");
      out.write("<!-- my custom js -->\n");
      out.write("<script src=\"js/custom.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("    if ($.cookie(\"rememberUser\") == \"true\"){\n");
      out.write("        $(\"#remember\").attr(\"checked\", true);\n");
      out.write("        $(\"#account\").val($.cookie(\"account\"));\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("\n");
      out.write("function rememberUser(){\n");
      out.write("    if ($(\"#remember\").is(':checked')){\n");
      out.write("        var account = $(\"#account\").val();\n");
      out.write("        $.cookie(\"rememberUser\", \"true\", { expires: 7 }); \t// 存储一个带7天期限的 cookie\n");
      out.write("        $.cookie(\"account\", account, { expires: 7 }); \t\t// 存储一个带7天期限的 cookie\n");
      out.write("    }\n");
      out.write("    else {\n");
      out.write("        $.cookie(\"rememberUser\", \"false\", { expires: -1 });\t// 删除 cookie\n");
      out.write("        $.cookie(\"account\", '', { expires: -1 });\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /login.jsp(87,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\t       \t\t\n");
        out.write("\t\t\t        \t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\t\t\t        \t\n");
        out.write("\t\t\t        \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
